---
- name: Install the Android SDK (OS X)
  homebrew: name=android-sdk state=present
  when: ansible_os_family == 'Darwin'

- name: Set Android Home in bash_profile
  lineinfile: dest=~/.bash_profile state=present line="export ANDROID_HOME=/usr/local/opt/android-sdk"

- name: Set Android SDK in bash_profile
  lineinfile: dest=~/.bash_profile state=present line="export ANDROID_SDK=/usr/local/opt/android-sdk"
