---

- name: Install nvm
  homebrew: name=nvm state=present

- name: Create nvm home
  file: path=~/.nvm state=directory

- name: Set nvm environment variables
  lineinfile: dest=~/.bash_profile line="export NVM_DIR=\"$HOME/.nvm\"" state=present create=yes

- name: Load nvm from bash_profile
  lineinfile: dest=~/.bash_profile line="source /usr/local/opt/nvm/nvm.sh" state=present create=yes

- name: Install node
  shell: source ~/.bash_profile && nvm install node

- name: Install yarn
  shell: source ~/.bash_profile && npm install -g yarn
